Sharprompt/Confirm.cs, Sharprompt/ConsoleScope.cs, Sharprompt/Error.cs, Sharprompt/Input.cs, Sharprompt/Password.cs, Sharprompt/Prompt.cs, Sharprompt/Select.cs, Sharprompt/Validators.cs
=> Avoid common keywords

Sharprompt/Sharprompt.csproj
=> Fixed small typo

Sharprompt/ConsoleRenderer.cs, Sharprompt/ConsoleScope.cs
=> Fixed incorrect cursor location

Sharprompt/ConsoleRenderer.cs, Sharprompt/Select.cs
=> Fixed rendering bug when handling long strings

Example/Example.csproj, Sharprompt/Confirm.cs, Sharprompt/Input.cs, Sharprompt/MultiSelect.cs, Sharprompt/Password.cs, Sharprompt/Prompt.cs, Sharprompt/Select.cs, Sharprompt/Sharprompt.csproj
- Fixed `MultiSelect` bug
- Use C# 8.0 feature
- Cleanup coding style
=> Refactoring and fixed minor bugs

Example/Program.cs, Sharprompt/MultiSelect.cs
=> Fixed MultiSelect minimum selection handling

Sharprompt/Drivers/DefaultConsoleDriver.cs
=> Adding cleanup at Ctrl+C interrupt

Sharprompt/Drivers/DefaultConsoleDriver.cs, Sharprompt/Internal/EastAsianWidth.cs
=> Improvement Full-width support

Sharprompt/Forms/MultiSelect.cs
=> Adding MultiSelect hint message

Sharprompt.Example/Program.cs, Sharprompt/Drivers/DefaultConsoleDriver.cs, Sharprompt/Drivers/IConsoleDriver.cs, Sharprompt/Drivers/WindowsConsoleDriver.cs, Sharprompt/Forms/Confirm.cs, Sharprompt/Forms/FormBase.cs, Sharprompt/Forms/FormRenderer.cs, Sharprompt/Forms/Input.cs, Sharprompt/Forms/MultiSelect.cs, Sharprompt/Forms/Password.cs, Sharprompt/Forms/Select.cs, Sharprompt/Internal/EastAsianWidth.cs
=> Changed to not delete input text after a failed validation

Sharprompt/Drivers/DefaultConsoleDriver.cs, Sharprompt/Drivers/IConsoleDriver.cs, Sharprompt/Forms/Confirm.cs, Sharprompt/Forms/FormBase.cs, Sharprompt/Forms/FormRenderer.cs, Sharprompt/Forms/Input.cs, Sharprompt/Forms/MultiSelect.cs, Sharprompt/Forms/Password.cs, Sharprompt/Forms/Select.cs, Sharprompt/Internal/ScreenBuffer.cs
=> Adding off-screen buffer

Sharprompt/Forms/Confirm.cs, Sharprompt/Forms/Input.cs
=> Fixed the behavior of validation when having default value

Sharprompt/Internal/Symbol.cs
=> Changed Symbol to be customizable

Sharprompt/Drivers/DefaultConsoleDriver.cs, Sharprompt/Internal/NativeMethods.cs
=> Fixed to explicitly enable VT100 on Windows

Sharprompt.Example/Program.cs, Sharprompt/Internal/EnumValue.cs, Sharprompt/Prompt.cs
=> Fixed crash when Enum is set to default value

Sharprompt/Validators.cs
=> Fixed Required validator for not string type

Sharprompt/Forms/Input.cs
=> Fixed default value condition

Sharprompt.Example/ExampleType.cs, Sharprompt.Example/Models/MyEnum.cs, Sharprompt.Example/Models/MyFormModel.cs, Sharprompt.Example/Program.cs, Sharprompt/Internal/ValidationAttributeAdapter.cs, Sharprompt/Prompt.AutoForms.cs, Sharprompt/Prompt.Base.cs, Sharprompt/Prompt.Customize.cs
Close #72
```csharp
public class MyFormModel
{
[Display(Prompt = "What's your name?", Order = 1)]
[Required]
public string Name { get; set; }
[Display(Prompt = "Select enum value", Order = 2)]
public MyEnum? MyEnum { get; set; }
[Display(Prompt = "Type new password", Order = 3)]
[DataType(DataType.Password)]
[Required]
[MinLength(8)]
public string Password { get; set; }
[Display(Prompt = "Are you ready?", Order = 4)]
public bool Ready { get; set; }
[Display(Prompt = "Select enum values", Order = 5)]
public IEnumerable<MyEnum> MyEnums { get; set; }
}
class Program
{
static void Main(string[] args)
{
// Annotation based form
var model = Prompt.AutoForms<MyFormModel>();
}
}
```
=> Adding basic AutoForms support

Sharprompt/Validators.cs
I needed to have different error messages displayed because I need them to be translated.
=> Added custom error message to validators

Sharprompt.Example/Models/MyEnum.cs, Sharprompt.Example/Program.cs, Sharprompt/Internal/EnumValue.cs
=> Fixed an error when Order property is not set

Sharprompt/Drivers/DefaultConsoleDriver.cs, Sharprompt/Drivers/IConsoleDriver.cs, Sharprompt/Forms/Input.cs, Sharprompt/Forms/MultiSelect.cs, Sharprompt/Forms/Password.cs, Sharprompt/Forms/Select.cs
=> Fixed rendering slowdown on consecutive keystrokes

Sharprompt/Forms/ConfirmForm.cs, Sharprompt/Forms/InputForm.cs, Sharprompt/Forms/MultiSelectForm.cs, Sharprompt/Forms/PasswordForm.cs, Sharprompt/Forms/SelectForm.cs, Sharprompt/Prompt.Basic.cs
=> Adding suffix for form implementation

Sharprompt.Example/ExampleType.cs, Sharprompt.Example/Program.cs, Sharprompt/Forms/ListForm.cs, Sharprompt/ListOptions.cs, Sharprompt/Prompt.Basic.cs
=> Added new `List` prompt type

Sharprompt/Drivers/DefaultConsoleDriver.cs, Sharprompt/Drivers/IConsoleDriver.cs, Sharprompt/Forms/ConfirmForm.cs, Sharprompt/Forms/FormBase.cs, Sharprompt/Forms/FormRenderer.cs, Sharprompt/Forms/InputForm.cs, Sharprompt/Forms/ListForm.cs, Sharprompt/Forms/MultiSelectForm.cs, Sharprompt/Forms/SelectForm.cs, Sharprompt/Internal/EastAsianWidth.cs, Sharprompt/Internal/OffscreenBuffer.cs, Sharprompt/Sharprompt.csproj
=> Refactoring validation mechanism

Sharprompt/Forms/MultiSelectForm.cs, Sharprompt/Forms/SelectForm.cs, Sharprompt/Internal/Paginator.cs
=> Adding pagination for `Select` and `MultiSelect`

README.md
Adding `Prompt.List` example and animation gif.
=> Adding `List` prompt example in README

Sharprompt/Prompt.AutoForms.cs
=> Fixed AutoForms multi-select error

Sharprompt/Internal/OffscreenBuffer.cs, Sharprompt/Prompt.Customize.cs
I couldn't find this feature while working on a project, then I had to make changes to Internal. Now we can change the symbol colors with the "DoneSymbolColor" and "PromptSymbolColor" properties on the ColorSchema class.
=> Symbol Color Changable

Sharprompt/Drivers/DefaultConsoleDriver.cs, Sharprompt/Drivers/IConsoleDriver.cs, Sharprompt/Forms/ConfirmForm.cs, Sharprompt/Forms/FormBase.cs, Sharprompt/Forms/FormRenderer.cs, Sharprompt/Forms/InputForm.cs, Sharprompt/Forms/ListForm.cs, Sharprompt/Forms/MultiSelectForm.cs, Sharprompt/Forms/PasswordForm.cs, Sharprompt/Forms/SelectForm.cs, Sharprompt/Internal/Cursor.cs, Sharprompt/Internal/EastAsianWidth.cs, Sharprompt/Internal/OffscreenBuffer.cs, Sharprompt/Internal/Paginator.cs, Sharprompt/Internal/RenderScope.cs, Sharprompt/Prompt.Customize.cs
=> Improve rendering performance

Sharprompt/Drivers/DefaultConsoleDriver.cs, Sharprompt/Forms/ConfirmForm.cs, Sharprompt/Forms/FormRenderer.cs, Sharprompt/Forms/InputForm.cs, Sharprompt/Forms/ListForm.cs, Sharprompt/Forms/PasswordForm.cs, Sharprompt/Internal/OffscreenBuffer.cs
- Fixed issue a cursor can't moved
- Fixed send `Ctrl+C` behavior on Linux
=> Fixed invalid cursor position

Sharprompt/Forms/ConfirmForm.cs, Sharprompt/Forms/InputForm.cs, Sharprompt/Forms/ListForm.cs, Sharprompt/Forms/MultiSelectForm.cs, Sharprompt/Forms/PasswordForm.cs, Sharprompt/Forms/SelectForm.cs, Sharprompt/Internal/TextInputBuffer.cs
Introduced `TextInputBuffer` class for console text input and cursor management.
=> Added a class for common processing of input text

Sharprompt/Forms/ConfirmForm.cs, Sharprompt/Forms/FormRenderer.cs, Sharprompt/Forms/InputForm.cs, Sharprompt/Forms/ListForm.cs, Sharprompt/Forms/MultiSelectForm.cs, Sharprompt/Forms/PasswordForm.cs, Sharprompt/Internal/EnumValue.cs, Sharprompt/Internal/OffscreenBuffer.cs, Sharprompt/Internal/Optional.cs, Sharprompt/Internal/TypeHelper.cs, Sharprompt/Internal/ValidatorsExtensions.cs, Sharprompt/Prompt.Basic.cs, Sharprompt/Validators.cs
Introduced `TypeHelper<T>` class for nullable and convertion handling
=> Streamlined nullable type handling

Sharprompt/Internal/TypeHelper.cs
=> Change to use `TypeDescriptor.GetConverter` for type change

Sharprompt.Example/Program.cs, Sharprompt/Forms/PasswordForm.cs, Sharprompt/PasswordOptions.cs, Sharprompt/Prompt.AutoForms.cs, Sharprompt/Prompt.Basic.cs
=> Password mask characters can now be changed

Sharprompt/Prompt.Basic.cs
=> Fixed `MultiSelect` text selector is never used

Sharprompt/Forms/MultiSelectForm.cs, Sharprompt/Forms/SelectForm.cs, Sharprompt/MultiSelectOptions.cs, Sharprompt/SelectOptions.cs
=> Adding pagination custom template

.github/workflows/build.yml, Sharprompt.Tests/EastAsianWidthTests.cs, Sharprompt.Tests/Sharprompt.Tests.csproj, Sharprompt.Tests/TextInputBufferTests.cs, Sharprompt.sln, Sharprompt/AssemblyInfo.cs, Sharprompt/Internal/EastAsianWidth.cs, Sharprompt/Internal/TextInputBuffer.cs
=> Support for handling of UTF-16 surrogate pairs

Sharprompt.Example/Program.cs, Sharprompt/Forms/InputForm.cs, Sharprompt/Forms/PasswordForm.cs, Sharprompt/InputOptions.cs, Sharprompt/Internal/OffscreenBuffer.cs, Sharprompt/PasswordOptions.cs, Sharprompt/Prompt.AutoForms.cs, Sharprompt/Prompt.Basic.cs
=> Adding placeholder support for `Input` and `Password`

README.md, Sharprompt.Example/Models/MyFormModel.cs, Sharprompt.Tests/PropertyMetadataTests.cs, Sharprompt/InlineItemsAttribute.cs, Sharprompt/Internal/IItemsProvider.cs, Sharprompt/Internal/PropertyMetadata.cs, Sharprompt/Internal/TypeHelper.cs, Sharprompt/MemberItemsAttribute.cs, Sharprompt/Prompt.Bind.cs
- Required field
- Add `[Required]` attribute
- Not provide default value
- Make nullable type
=> Fixed `Prompt.Bind<T>` handle default value and improvement data source

Sharprompt.Tests/PaginatorTests.cs, Sharprompt/Internal/Paginator.cs
=> Fixed paginator crash when list is empty

Sharprompt/Forms/InputForm.cs, Sharprompt/Internal/TextInputBuffer.cs
=> Support navigating in InputForm with Home and End keys

Sharprompt/Drivers/DefaultConsoleDriver.cs
=> Restore console input cancellation settings

Sharprompt/Drivers/DefaultConsoleDriver.cs
=> Added enhanced checking of interactive environments

Sharprompt/Forms/ConfirmForm.cs, Sharprompt/Forms/FormBase.cs, Sharprompt/Forms/FormRenderer.cs, Sharprompt/Forms/InputForm.cs, Sharprompt/Forms/ListForm.cs, Sharprompt/Forms/MultiSelectForm.cs, Sharprompt/Forms/PasswordForm.cs, Sharprompt/Forms/SelectForm.cs, Sharprompt/Forms/TextFormBase.cs, Sharprompt/InlineItemsAttribute.cs, Sharprompt/Internal/EnumItemsProvider.cs, Sharprompt/Internal/IItemsProvider.cs, Sharprompt/Internal/NullItemsProvider.cs, Sharprompt/Internal/PropertyMetadata.cs, Sharprompt/MemberItemsAttribute.cs, Sharprompt/Prompt.Basic.cs, Sharprompt/Prompt.Bind.cs, Sharprompt/Prompt.Configuration.cs, Sharprompt/SelectOptions.cs
- `FormBase<T>`
- Implement essential functions for forms
- `TextFormBase<T>`
- Advanced text input (e.g., cursor movement) implemented
=> Rearchitecture of each form implementation

Sharprompt/Internal/Paginator.cs
=> Auto selection on single filtered item

Sharprompt/Internal/Paginator.cs
=> Fixed negative pagesize

Sharprompt/Forms/FormRenderer.cs, Sharprompt/Forms/MultiSelectForm.cs, Sharprompt/Forms/SelectForm.cs, Sharprompt/Internal/Paginator.cs, Sharprompt/MultiSelectOptions.cs, Sharprompt/PromptCanceledException.cs, Sharprompt/SelectOptions.cs
=> Added an option to jump to the previous/next page when selecting an item in Select / MultiSelect
